services:
  app:
    build:
      context: .
      dockerfile: ./deployment/php/php.dockerfile
    environment:
      DOPPLER_TOKEN: "${DOPPLER_TOKEN}"
    image: laravel-ci-cd
    container_name: laravel-ci-cd
    restart: always
    volumes: [ ]
    networks:
      - personal
  nginx:
    volumes: [ ]
