services:
  laravel_ci_cd_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DOPPLER_TOKEN: "${DOPPLER_STAGING_TOKEN}"
    image: laravel-ci-cd
    container_name: laravel-ci-cd
    restart: always
    working_dir: /var/www
    volumes:
      - ..:/var/www
      - ../vendor:/var/www/vendor
    networks:
      - personal
  laravel_ci_cd_nginx:
    image: nginx:1.26.2-alpine
    container_name: laravel-ci-cd-nginx
    restart: always
    ports:
      - "127.0.0.1:9001:80"
    volumes:
      - ..:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel_ci_cd_app
    networks:
      - personal
networks:
  personal:
    name: personal
    external: true
